/**
 * ACL4SSR Configuration - Pre-parsed for CF Workers
 */

export const CONFIG = {
    rulesets: [
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/refs/heads/main/Clash/CFnat.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list' },
        { group: '🛑 全球拦截', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list' },
        { group: '🍃 应用净化', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list' },
        { group: '🍃 应用净化', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/adobe.list' },
        { group: '🍃 应用净化', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/IDM.list' },
        { group: '📢 谷歌FCM', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list' },
        { group: 'Ⓜ️ 微软服务', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list' },
        { group: '🍎 苹果服务', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list' },
        { group: '📲 电报信息', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list' },
        { group: '🤖 OpenAi', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list' },
        { group: '🤖 OpenAi', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/juewuy/ShellClash/master/rules/ai.list' },
        { group: '🤖 OpenAi', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Copilot.list' },
        { group: '🤖 OpenAi', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/GithubCopilot.list' },
        { group: '🤖 OpenAi', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Claude.list' },
        { group: '🛸 Antigravity', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ryty1/ACL4SSR/master/Clash/antigravity.list' },
        { group: '📹 油管视频', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list' },
        { group: '🎥 奈飞视频', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list' },
        { group: '🌍 国外媒体', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list' },
        { group: '🌍 国外媒体', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Emby.list' },
        { group: '🚀 节点选择', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list' },
        { group: '🚀 节点选择', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/CMBlog.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/ChinaCompanyDomain.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ryty1/ACL4SSR/master/Clash/zdy.list' },
        { group: '🎯 全球直连', isBuiltin: true, type: 'GEOIP', value: 'CN' },
        { group: '🐟 漏网之鱼', isBuiltin: true, type: 'FINAL' }
    ],

    proxyGroups: [
        // Functional groups
        { name: '🚀 节点选择', type: 'select', proxies: ['♻️ 自动选择', '☑️ 手动切换', '🇭🇰 香港节点', '🇲🇴 澳门节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇰🇷 韩国节点', '🇺🇸 美国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇳🇱 荷兰节点', '🇷🇺 俄罗斯节点', '🇨🇦 加拿大节点', '🇦🇺 澳洲节点', '🇮🇳 印度节点', 'DIRECT'] },
        { name: '☑️ 手动切换', type: 'select', filter: '.*' },
        { name: '♻️ 自动选择', type: 'url-test', filter: '.*', url: 'http://www.gstatic.com/generate_204', interval: 300, tolerance: 50 },
        { name: '📹 油管视频', type: 'select', proxies: ['🚀 节点选择', '♻️ 自动选择', '☑️ 手动切换', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇮🇳 印度节点', '🇦🇺 澳洲节点', 'DIRECT'] },
        { name: '🎥 奈飞视频', type: 'select', proxies: ['🚀 节点选择', '♻️ 自动选择', '☑️ 手动切换', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇮🇳 印度节点', '🇦🇺 澳洲节点', '🇨🇦 加拿大节点', 'DIRECT'] },
        { name: '🌍 国外媒体', type: 'select', proxies: ['🚀 节点选择', '♻️ 自动选择', '☑️ 手动切换', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇮🇳 印度节点', '🇦🇺 澳洲节点', 'DIRECT'] },
        { name: '📲 电报信息', type: 'select', proxies: ['🚀 节点选择', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇳🇱 荷兰节点', '🇮🇳 印度节点', '🇹🇷 土耳其节点', 'DIRECT'] },
        { name: '🤖 OpenAi', type: 'select', proxies: ['🚀 节点选择', '♻️ 自动选择', '☑️ 手动切换', '🇺🇸 美国节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇮🇳 印度节点', '🇨🇦 加拿大节点', '🇦🇺 澳洲节点', '🇳🇱 荷兰节点', '🇮🇪 爱尔兰节点', '🇫🇮 芬兰节点', '🇸🇪 瑞典节点', 'DIRECT'] },
        { name: '🛸 Antigravity', type: 'select', proxies: ['♻️ 自动选择', '☑️ 手动切换', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇳🇱 荷兰节点', '🇷🇺 俄罗斯节点', '🇮🇳 印度节点', '🇹🇷 土耳其节点', '🇨🇦 加拿大节点', '🇦🇺 澳洲节点', '🇫🇮 芬兰节点', '🇸🇪 瑞典节点', '🇨🇭 瑞士节点', 'DIRECT'] },
        { name: 'Ⓜ️ 微软服务', type: 'select', proxies: ['🎯 全球直连', '🚀 节点选择', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇮🇳 印度节点', '🇳🇱 荷兰节点', '🇮🇪 爱尔兰节点', 'DIRECT'] },
        { name: '🍎 苹果服务', type: 'select', proxies: ['🚀 节点选择', '🎯 全球直连', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇮🇳 印度节点', '🇦🇺 澳洲节点', 'DIRECT'] },
        { name: '📢 谷歌FCM', type: 'select', proxies: ['🚀 节点选择', '🎯 全球直连', '♻️ 自动选择', '☑️ 手动切换', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇮🇳 印度节点', 'DIRECT'] },
        { name: '🎯 全球直连', type: 'select', proxies: ['DIRECT', '🚀 节点选择', '♻️ 自动选择', '☑️ 手动切换'] },
        { name: '🛑 全球拦截', type: 'select', proxies: ['REJECT', 'DIRECT'] },
        { name: '🍃 应用净化', type: 'select', proxies: ['REJECT', 'DIRECT'] },
        { name: '🐟 漏网之鱼', type: 'select', proxies: ['🚀 节点选择', '🎯 全球直连', '♻️ 自动选择', '☑️ 手动切换', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇳🇱 荷兰节点', '🇮🇳 印度节点', '🇫🇮 芬兰节点', 'DIRECT'] },

        // Country groups
        { name: '🇭🇰 香港节点', type: 'select', filter: '(港|HK|hk|Hong Kong|HongKong|hongkong|HKG)' },
        { name: '🇲🇴 澳门节点', type: 'select', filter: '(澳门|MO|Macau|macao)' },
        { name: '🇹🇼 台湾节点', type: 'select', filter: '(台|新北|彰化|TW|Taiwan|taipei)' },
        { name: '🇯🇵 日本节点', type: 'select', filter: '(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|tokyo|osaka)' },
        { name: '🇰🇷 韩国节点', type: 'select', filter: '(韩国|韩|KR|Korea|KOR|首尔|seoul|春川)' },
        { name: '🇸🇬 狮城节点', type: 'select', filter: '(新加坡|坡|狮城|SG|Singapore)' },
        { name: '🇺🇸 美国节点', type: 'select', filter: '(美国|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|USA|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC)' },
        { name: '🇬🇧 英国节点', type: 'select', filter: '(英国|UK|GB|United Kingdom|Britain|伦敦|London|曼彻斯特)' },
        { name: '🇩🇪 德国节点', type: 'select', filter: '(德国|DE|Germany|法兰克福|柏林|慕尼黑|Frankfurt)' },
        { name: '🇫🇷 法国节点', type: 'select', filter: '(法国|FR|France|巴黎|Paris|马赛)' },
        { name: '🇳🇱 荷兰节点', type: 'select', filter: '(荷兰|NL|Netherlands|阿姆斯特丹|Amsterdam)' },
        { name: '🇷🇺 俄罗斯节点', type: 'select', filter: '(俄罗斯|俄|RU|Russia|莫斯科|圣彼得堡|Moscow)' },
        { name: '🇨🇦 加拿大节点', type: 'select', filter: '(加拿大|CA|Canada|多伦多|温哥华|蒙特利尔)' },
        { name: '🇦🇺 澳洲节点', type: 'select', filter: '(澳洲|澳大利亚|AU|Australia|悉尼|墨尔本|Sydney|Melbourne)' },
        { name: '🇮🇳 印度节点', type: 'select', filter: '(印度|India|孟买|新德里|Mumbai|Delhi)' },
        { name: '🇹🇷 土耳其节点', type: 'select', filter: '(土耳其|Turkey|伊斯坦布尔|安卡拉)' },
        { name: '🇮🇪 爱尔兰节点', type: 'select', filter: '(爱尔兰|Ireland|都柏林)' },
        { name: '🇫🇮 芬兰节点', type: 'select', filter: '(芬兰|Finland|赫尔辛基)' },
        { name: '🇸🇪 瑞典节点', type: 'select', filter: '(瑞典|Sweden|斯德哥尔摩)' },
        { name: '🇨🇭 瑞士节点', type: 'select', filter: '(瑞士|Switzerland|苏黎世|日内瓦)' },
        { name: '🇲🇾 马来节点', type: 'select', filter: '(马来西亚|马来|MY|Malaysia|吉隆坡)' },
        { name: '🇹🇭 泰国节点', type: 'select', filter: '(泰国|TH|Thailand|曼谷)' },
        { name: '🇻🇳 越南节点', type: 'select', filter: '(越南|VN|Vietnam|胡志明|河内)' },
        { name: '🇵🇭 菲律宾节点', type: 'select', filter: '(菲律宾|PH|Philippines|马尼拉)' },
        { name: '🇮🇩 印尼节点', type: 'select', filter: '(印度尼西亚|印尼|ID|Indonesia|雅加达)' },
        { name: '🇧🇷 巴西节点', type: 'select', filter: '(巴西|Brazil|圣保罗|里约)' },
        { name: '🇦🇷 阿根廷节点', type: 'select', filter: '(阿根廷|Argentina|布宜诺斯艾利斯)' },
        { name: '🇲🇽 墨西哥节点', type: 'select', filter: '(墨西哥|Mexico|墨城)' },
        { name: '🇿🇦 南非节点', type: 'select', filter: '(南非|South Africa|约翰内斯堡|开普敦)' },
        { name: '🇪🇬 埃及节点', type: 'select', filter: '(埃及|Egypt|开罗)' },
        { name: '🇳🇬 尼日利亚节点', type: 'select', filter: '(尼日利亚|Nigeria|拉各斯)' },
        { name: '🇰🇪 肯尼亚节点', type: 'select', filter: '(肯尼亚|Kenya|内罗毕)' },
        { name: '🇦🇪 阿联酋节点', type: 'select', filter: '(阿联酋|United Arab Emirates|迪拜|Dubai|阿布扎比)' },
        { name: '🇸🇦 沙特节点', type: 'select', filter: '(沙特|Saudi Arabia|沙特阿拉伯|利雅得)' },
        { name: '🇮🇱 以色列节点', type: 'select', filter: '(以色列|Israel|特拉维夫)' },
        { name: '🇳🇿 新西兰节点', type: 'select', filter: '(新西兰|New Zealand|奥克兰)' }
    ]
};
