/**
 * ACL4SSR Configuration - Pre-parsed for CF Workers
 */

export const CONFIG = {
    rulesets: [
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/CFnat.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list' },
        { group: '🛑 全球拦截', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list' },
        { group: '🍃 应用净化', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list' },
        { group: '🍃 应用净化', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/adobe.list' },
        { group: '🍃 应用净化', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/IDM.list' },
        { group: '📢 谷歌FCM', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list' },
        { group: 'Ⓜ️ 微软服务', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list' },
        { group: '🍎 苹果服务', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list' },
        { group: '📲 电报信息', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list' },
        { group: '🤖 OpenAi', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list' },
        { group: '🤖 OpenAi', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/juewuy/ShellClash/master/rules/ai.list' },
        { group: '🤖 OpenAi', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Copilot.list' },
        { group: '🤖 OpenAi', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/GithubCopilot.list' },
        { group: '🤖 OpenAi', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Claude.list' },
        { group: '🛸 Antigravity', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ryty1/ACL4SSR/master/Clash/antigravity.list' },
        { group: '📹 油管视频', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list' },
        { group: '🎥 奈飞视频', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list' },
        { group: '🌍 国外媒体', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list' },
        { group: '🌍 国外媒体', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Emby.list' },
        { group: '🚀 节点选择', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list' },
        { group: '🚀 节点选择', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/CMBlog.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/ChinaCompanyDomain.list' },
        { group: '🎯 全球直连', source: 'https://gh-proxy.com/https://raw.githubusercontent.com/ryty1/ACL4SSR/master/Clash/zdy.list' },
        { group: '🎯 全球直连', isBuiltin: true, type: 'GEOIP', value: 'CN' },
        { group: '🐟 漏网之鱼', isBuiltin: true, type: 'FINAL' }
    ],

    proxyGroups: [
        { name: '🚀 节点选择', type: 'select', proxies: ['♻️ 自动选择', '⚖️ 负载均衡', '☑️ 手动切换', '🇭🇰 香港节点', '🇲🇴 澳门节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇰🇷 韩国节点', '🇲🇳 蒙古节点', '🇲🇾 马来节点', '🇹🇭 泰国节点', '🇻🇳 越南节点', '🇵🇭 菲律宾节点', '🇮🇩 印尼节点', '🇰🇭 柬埔寨节点', '🇲🇲 缅甸节点', '🇱🇦 老挝节点', '🇮🇳 印度节点', '🇵🇰 巴基斯坦节点', '🇧🇩 孟加拉节点', '🇰🇿 哈萨克节点', '🇦🇪 阿联酋节点', '🇸🇦 沙特节点', '🇮🇱 以色列节点', '🇹🇷 土耳其节点', '🇮🇷 伊朗节点', '🇮🇶 伊拉克节点', '🇶🇦 卡塔尔节点', '🇺🇸 美国节点', '🇨🇦 加拿大节点', '🇲🇽 墨西哥节点', '🇵🇦 巴拿马节点', '🇧🇷 巴西节点', '🇦🇷 阿根廷节点', '🇨🇱 智利节点', '🇨🇴 哥伦比亚节点', '🇵🇪 秘鲁节点', '🇻🇪 委内瑞拉节点', '🇪🇨 厄瓜多尔节点', '🇺🇾 乌拉圭节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇳🇱 荷兰节点', '🇧🇪 比利时节点', '🇨🇭 瑞士节点', '🇦🇹 奥地利节点', '🇮🇪 爱尔兰节点', '🇸🇪 瑞典节点', '🇳🇴 挪威节点', '🇫🇮 芬兰节点', '🇩🇰 丹麦节点', '🇮🇸 冰岛节点', '🇮🇹 意大利节点', '🇪🇸 西班牙节点', '🇵🇹 葡萄牙节点', '🇬🇷 希腊节点', '🇷🇺 俄罗斯节点', '🇺🇦 乌克兰节点', '🇧🇾 白俄罗斯节点', '🇵🇱 波兰节点', '🇨🇿 捷克节点', '🇸🇰 斯洛伐克节点', '🇭🇺 匈牙利节点', '🇷🇴 罗马尼亚节点', '🇧🇬 保加利亚节点', '🇲🇩 摩尔多瓦节点', '🇱🇻 拉脱维亚节点', '🇱🇹 立陶宛节点', '🇪🇪 爱沙尼亚节点', '🇸🇮 斯洛文尼亚节点', '🇭🇷 克罗地亚节点', '🇷🇸 塞尔维亚节点', '🇱🇺 卢森堡节点', '🇦🇺 澳洲节点', '🇳🇿 新西兰节点', '🇿🇦 南非节点', '🇪🇬 埃及节点', '🇳🇬 尼日利亚节点', '🇰🇪 肯尼亚节点', 'DIRECT'] },
        { name: '☑️ 手动切换', type: 'select', filter: '.*' },
        { name: '♻️ 自动选择', type: 'url-test', filter: '.*', url: 'http://www.gstatic.com/generate_204', interval: 300, tolerance: 50 },
        { name: '⚖️ 负载均衡', type: 'load-balance', proxies: ['☁️ Snippets'], url: 'http://www.gstatic.com/generate_204', interval: 300, strategy: 'consistent-hashing' },
        { name: '📹 油管视频', type: 'select', proxies: ['🚀 节点选择', '♻️ 自动选择', '☑️ 手动切换', '⚖️ 负载均衡', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇮🇳 印度节点', '🇦🇺 澳洲节点', 'DIRECT'] },
        { name: '🎥 奈飞视频', type: 'select', proxies: ['🚀 节点选择', '♻️ 自动选择', '☑️ 手动切换', '⚖️ 负载均衡', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇮🇳 印度节点', '🇦🇺 澳洲节点', '🇨🇦 加拿大节点', 'DIRECT'] },
        { name: '🌍 国外媒体', type: 'select', proxies: ['🚀 节点选择', '♻️ 自动选择', '☑️ 手动切换', '⚖️ 负载均衡', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇮🇳 印度节点', '🇦🇺 澳洲节点', 'DIRECT'] },
        { name: '📲 电报信息', type: 'select', proxies: ['🚀 节点选择', '☁️ Snippets', '🇭🇰 香港节点', '☑️ 手动切换', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇳🇱 荷兰节点', '🇮🇳 印度节点', '🇹🇷 土耳其节点', 'DIRECT'] },
        { name: '🤖 OpenAi', type: 'select', proxies: ['🚀 节点选择', '♻️ 自动选择', '☑️ 手动切换', '🇺🇸 美国节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇮🇳 印度节点', '🇨🇦 加拿大节点', '🇦🇺 澳洲节点', '🇳🇱 荷兰节点', '🇮🇪 爱尔兰节点', '🇫🇮 芬兰节点', '🇸🇪 瑞典节点', 'DIRECT'] },
        { name: '🛸 Antigravity', type: 'select', proxies: ['♻️ 自动选择', '☑️ 手动切换', '☁️ Snippets', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇮🇳 印度节点', '🇹🇷 土耳其节点', '🇨🇦 加拿大节点', '🇦🇺 澳洲节点', '🇫🇮 芬兰节点', '🇸🇪 瑞典节点', '🇨🇭 瑞士节点', 'DIRECT'] },
        { name: 'Ⓜ️ 微软服务', type: 'select', proxies: ['🎯 全球直连', '🚀 节点选择', '☁️ Snippets', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇮🇳 印度节点', '🇦🇺 澳洲节点', 'DIRECT'] },
        { name: '🍎 苹果服务', type: 'select', proxies: ['🎯 全球直连', '🚀 节点选择', '☁️ Snippets', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇮🇳 印度节点', '🇦🇺 澳洲节点', 'DIRECT'] },
        { name: '📢 谷歌FCM', type: 'select', proxies: ['🚀 节点选择', '🎯 全球直连', '♻️ 自动选择', '☑️ 手动切换', '☁️ Snippets', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇮🇳 印度节点', 'DIRECT'] },
        { name: '🎯 全球直连', type: 'select', proxies: ['DIRECT', '🚀 节点选择', '♻️ 自动选择', '☑️ 手动切换'] },
        { name: '🛑 全球拦截', type: 'select', proxies: ['REJECT', 'DIRECT'] },
        { name: '🍃 应用净化', type: 'select', proxies: ['REJECT', 'DIRECT'] },
        { name: '🐟 漏网之鱼', type: 'select', proxies: ['🚀 节点选择', '🎯 全球直连', '♻️ 自动选择', '☑️ 手动切换', '🇭🇰 香港节点', '🇹🇼 台湾节点', '🇯🇵 日本节点', '🇸🇬 狮城节点', '🇺🇸 美国节点', '🇰🇷 韩国节点', '🇬🇧 英国节点', '🇩🇪 德国节点', '🇫🇷 法国节点', '🇳🇱 荷兰节点', '🇮🇳 印度节点', '🇫🇮 芬兰节点', 'DIRECT'] },

        { name: '☁️ Snippets', type: 'url-test', url: 'http://www.gstatic.com/generate_204', interval: 300, tolerance: 50, filter: '(snippets|Snippets|Sni|sni|Snip|snip)' },
        { name: '🇭🇰 香港节点', type: 'select', filter: '(港|HK|hk|Hong Kong|HongKong|hongkong|HKG)' },
        { name: '🇲🇴 澳门节点', type: 'select', filter: '(澳门|MO|Macau|macao)' },
        { name: '🇹🇼 台湾节点', type: 'select', filter: '(台|新北|彰化|TW|Taiwan|taipei)' },
        { name: '🇯🇵 日本节点', type: 'select', filter: '(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|tokyo|osaka)' },
        { name: '🇰🇷 韩国节点', type: 'select', filter: '(韩国|韩|KR|Korea|KOR|首尔|seoul|春川)' },
        { name: '🇲🇳 蒙古节点', type: 'select', filter: '(蒙古|Mongolia|乌兰巴托)' },
        { name: '🇸🇬 狮城节点', type: 'select', filter: '(新加坡|坡|狮城|SG|Singapore)' },
        { name: '🇲🇾 马来节点', type: 'select', filter: '(马来西亚|马来|MY|Malaysia|吉隆坡)' },
        { name: '🇹🇭 泰国节点', type: 'select', filter: '(泰国|TH|Thailand|曼谷)' },
        { name: '🇻🇳 越南节点', type: 'select', filter: '(越南|VN|Vietnam|胡志明|河内)' },
        { name: '🇵🇭 菲律宾节点', type: 'select', filter: '(菲律宾|PH|Philippines|马尼拉)' },
        { name: '🇮🇩 印尼节点', type: 'select', filter: '(印度尼西亚|印尼|ID|Indonesia|雅加达)' },
        { name: '🇰🇭 柬埔寨节点', type: 'select', filter: '(柬埔寨|Cambodia|金边)' },
        { name: '🇲🇲 缅甸节点', type: 'select', filter: '(缅甸|Myanmar|仰光)' },
        { name: '🇱🇦 老挝节点', type: 'select', filter: '(老挝|Laos|万象)' },
        { name: '🇧🇳 文莱节点', type: 'select', filter: '(文莱|Brunei)' },
        { name: '🇹🇱 东帝汶节点', type: 'select', filter: '(东帝汶|Timor-Leste)' },
        { name: '🇮🇳 印度节点', type: 'select', filter: '(印度|India|孟买|新德里|Mumbai|Delhi)' },
        { name: '🇵🇰 巴基斯坦节点', type: 'select', filter: '(巴基斯坦|Pakistan|卡拉奇|伊斯兰堡)' },
        { name: '🇧🇩 孟加拉节点', type: 'select', filter: '(孟加拉|Bangladesh|达卡)' },
        { name: '🇳🇵 尼泊尔节点', type: 'select', filter: '(尼泊尔|Nepal|加德满都)' },
        { name: '🇱🇰 斯里兰卡节点', type: 'select', filter: '(斯里兰卡|Sri Lanka|科伦坡)' },
        { name: '🇧🇹 不丹节点', type: 'select', filter: '(不丹|Bhutan)' },
        { name: '🇲🇻 马尔代夫节点', type: 'select', filter: '(马尔代夫|Maldives|马累)' },
        { name: '🇦🇫 阿富汗节点', type: 'select', filter: '(阿富汗|Afghanistan|喀布尔)' },
        { name: '🇰🇿 哈萨克节点', type: 'select', filter: '(哈萨克斯坦|哈萨克|Kazakhstan|阿拉木图)' },
        { name: '🇺🇿 乌兹别克节点', type: 'select', filter: '(乌兹别克斯坦|乌兹别克|Uzbekistan|塔什干)' },
        { name: '🇹🇲 土库曼节点', type: 'select', filter: '(土库曼斯坦|土库曼|Turkmenistan)' },
        { name: '🇹🇯 塔吉克节点', type: 'select', filter: '(塔吉克斯坦|塔吉克|Tajikistan)' },
        { name: '🇰🇬 吉尔吉斯节点', type: 'select', filter: '(吉尔吉斯斯坦|吉尔吉斯|Kyrgyzstan)' },
        { name: '🇦🇿 阿塞拜疆节点', type: 'select', filter: '(阿塞拜疆|Azerbaijan|巴库)' },
        { name: '🇦🇲 亚美尼亚节点', type: 'select', filter: '(亚美尼亚|Armenia|埃里温)' },
        { name: '🇬🇪 格鲁吉亚节点', type: 'select', filter: '(格鲁吉亚|Georgia|第比利斯)' },
        { name: '🇦🇪 阿联酋节点', type: 'select', filter: '(阿联酋|United Arab Emirates|迪拜|Dubai|阿布扎比)' },
        { name: '🇸🇦 沙特节点', type: 'select', filter: '(沙特|Saudi Arabia|沙特阿拉伯|利雅得)' },
        { name: '🇮🇱 以色列节点', type: 'select', filter: '(以色列|Israel|特拉维夫)' },
        { name: '🇹🇷 土耳其节点', type: 'select', filter: '(土耳其|Turkey|伊斯坦布尔|安卡拉)' },
        { name: '🇮🇷 伊朗节点', type: 'select', filter: '(伊朗|Iran|德黑兰)' },
        { name: '🇮🇶 伊拉克节点', type: 'select', filter: '(伊拉克|Iraq|巴格达)' },
        { name: '🇶🇦 卡塔尔节点', type: 'select', filter: '(卡塔尔|Qatar|多哈)' },
        { name: '🇰🇼 科威特节点', type: 'select', filter: '(科威特|Kuwait)' },
        { name: '🇴🇲 阿曼节点', type: 'select', filter: '(阿曼|Oman|马斯喀特)' },
        { name: '🇧🇭 巴林节点', type: 'select', filter: '(巴林|Bahrain|麦纳麦)' },
        { name: '🇯🇴 约旦节点', type: 'select', filter: '(约旦|Jordan|安曼)' },
        { name: '🇱🇧 黎巴嫩节点', type: 'select', filter: '(黎巴嫩|Lebanon|贝鲁特)' },
        { name: '🇸🇾 叙利亚节点', type: 'select', filter: '(叙利亚|Syria|大马士革)' },
        { name: '🇾🇪 也门节点', type: 'select', filter: '(也门|Yemen|萨那)' },
        { name: '🇵🇸 巴勒斯坦节点', type: 'select', filter: '(巴勒斯坦|Palestine)' },
        { name: '🇺🇸 美国节点', type: 'select', filter: '(美国|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|USA|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC)' },
        { name: '🇨🇦 加拿大节点', type: 'select', filter: '(加拿大|CA|Canada|多伦多|温哥华|蒙特利尔)' },
        { name: '🇲🇽 墨西哥节点', type: 'select', filter: '(墨西哥|Mexico|墨城)' },
        { name: '🇵🇦 巴拿马节点', type: 'select', filter: '(巴拿马|Panama)' },
        { name: '🇨🇷 哥斯达黎加节点', type: 'select', filter: '(哥斯达黎加|Costa Rica)' },
        { name: '🇬🇹 危地马拉节点', type: 'select', filter: '(危地马拉|Guatemala)' },
        { name: '🇭🇳 洪都拉斯节点', type: 'select', filter: '(洪都拉斯|Honduras)' },
        { name: '🇳🇮 尼加拉瓜节点', type: 'select', filter: '(尼加拉瓜|Nicaragua)' },
        { name: '🇸🇻 萨尔瓦多节点', type: 'select', filter: '(萨尔瓦多|El Salvador)' },
        { name: '🇧🇿 伯利兹节点', type: 'select', filter: '(伯利兹|Belize)' },
        { name: '🇨🇺 古巴节点', type: 'select', filter: '(古巴|Cuba|哈瓦那)' },
        { name: '🇩🇴 多米尼加节点', type: 'select', filter: '(多米尼加|Dominican|圣多明各)' },
        { name: '🇯🇲 牙买加节点', type: 'select', filter: '(牙买加|Jamaica|金斯敦)' },
        { name: '🇭🇹 海地节点', type: 'select', filter: '(海地|Haiti)' },
        { name: '🇧🇸 巴哈马节点', type: 'select', filter: '(巴哈马|Bahamas)' },
        { name: '🇧🇧 巴巴多斯节点', type: 'select', filter: '(巴巴多斯|Barbados)' },
        { name: '🇹🇹 特立尼达节点', type: 'select', filter: '(特立尼达|Trinidad)' },
        { name: '🇵🇷 波多黎各节点', type: 'select', filter: '(波多黎各|Puerto Rico)' },
        { name: '🇧🇷 巴西节点', type: 'select', filter: '(巴西|Brazil|圣保罗|里约)' },
        { name: '🇦🇷 阿根廷节点', type: 'select', filter: '(阿根廷|Argentina|布宜诺斯艾利斯)' },
        { name: '🇨🇱 智利节点', type: 'select', filter: '(智利|Chile|圣地亚哥)' },
        { name: '🇨🇴 哥伦比亚节点', type: 'select', filter: '(哥伦比亚|Colombia|波哥大)' },
        { name: '🇵🇪 秘鲁节点', type: 'select', filter: '(秘鲁|Peru|利马)' },
        { name: '🇻🇪 委内瑞拉节点', type: 'select', filter: '(委内瑞拉|Venezuela|加拉加斯)' },
        { name: '🇪🇨 厄瓜多尔节点', type: 'select', filter: '(厄瓜多尔|Ecuador|基多)' },
        { name: '🇺🇾 乌拉圭节点', type: 'select', filter: '(乌拉圭|Uruguay|蒙得维的亚)' },
        { name: '🇧🇴 玻利维亚节点', type: 'select', filter: '(玻利维亚|Bolivia|拉巴斯)' },
        { name: '🇵🇾 巴拉圭节点', type: 'select', filter: '(巴拉圭|Paraguay|亚松森)' },
        { name: '🇬🇾 圭亚那节点', type: 'select', filter: '(圭亚那|Guyana)' },
        { name: '🇸🇷 苏里南节点', type: 'select', filter: '(苏里南|Suriname)' },
        { name: '🇬🇫 法属圭亚那节点', type: 'select', filter: '(法属圭亚那|French Guiana)' },
        { name: '🇬🇧 英国节点', type: 'select', filter: '(英国|UK|GB|United Kingdom|Britain|伦敦|London|曼彻斯特)' },
        { name: '🇩🇪 德国节点', type: 'select', filter: '(德国|DE|Germany|法兰克福|柏林|慕尼黑|Frankfurt)' },
        { name: '🇫🇷 法国节点', type: 'select', filter: '(法国|FR|France|巴黎|Paris|马赛)' },
        { name: '🇳🇱 荷兰节点', type: 'select', filter: '(荷兰|NL|Netherlands|阿姆斯特丹|Amsterdam)' },
        { name: '🇧🇪 比利时节点', type: 'select', filter: '(比利时|Belgium|布鲁塞尔)' },
        { name: '🇱🇺 卢森堡节点', type: 'select', filter: '(卢森堡|Luxembourg)' },
        { name: '🇨🇭 瑞士节点', type: 'select', filter: '(瑞士|Switzerland|苏黎世|日内瓦)' },
        { name: '🇦🇹 奥地利节点', type: 'select', filter: '(奥地利|Austria|维也纳)' },
        { name: '🇮🇪 爱尔兰节点', type: 'select', filter: '(爱尔兰|Ireland|都柏林)' },
        { name: '🇲🇨 摩纳哥节点', type: 'select', filter: '(摩纳哥|Monaco)' },
        { name: '🇱🇮 列支敦士登节点', type: 'select', filter: '(列支敦士登|Liechtenstein)' },
        { name: '🇦🇩 安道尔节点', type: 'select', filter: '(安道尔|Andorra)' },
        { name: '🇸🇪 瑞典节点', type: 'select', filter: '(瑞典|Sweden|斯德哥尔摩)' },
        { name: '🇳🇴 挪威节点', type: 'select', filter: '(挪威|Norway|奥斯陆)' },
        { name: '🇫🇮 芬兰节点', type: 'select', filter: '(芬兰|Finland|赫尔辛基)' },
        { name: '🇩🇰 丹麦节点', type: 'select', filter: '(丹麦|Denmark|哥本哈根)' },
        { name: '🇮🇸 冰岛节点', type: 'select', filter: '(冰岛|Iceland|雷克雅未克)' },
        { name: '🇫🇴 法罗群岛节点', type: 'select', filter: '(法罗群岛|Faroe)' },
        { name: '🇬🇱 格陵兰节点', type: 'select', filter: '(格陵兰|Greenland)' },
        { name: '🇮🇹 意大利节点', type: 'select', filter: '(意大利|Italy|米兰|罗马|都灵)' },
        { name: '🇪🇸 西班牙节点', type: 'select', filter: '(西班牙|Spain|马德里|巴塞罗那)' },
        { name: '🇵🇹 葡萄牙节点', type: 'select', filter: '(葡萄牙|Portugal|里斯本)' },
        { name: '🇬🇷 希腊节点', type: 'select', filter: '(希腊|Greece|雅典)' },
        { name: '🇨🇾 塞浦路斯节点', type: 'select', filter: '(塞浦路斯|Cyprus|尼科西亚)' },
        { name: '🇲🇹 马耳他节点', type: 'select', filter: '(马耳他|Malta|瓦莱塔)' },
        { name: '🇸🇲 圣马力诺节点', type: 'select', filter: '(圣马力诺|San Marino)' },
        { name: '🇻🇦 梵蒂冈节点', type: 'select', filter: '(梵蒂冈|Vatican)' },
        { name: '🇦🇱 阿尔巴尼亚节点', type: 'select', filter: '(阿尔巴尼亚|Albania|地拉那)' },
        { name: '🇲🇰 北马其顿节点', type: 'select', filter: '(北马其顿|马其顿|North Macedonia)' },
        { name: '🇽🇰 科索沃节点', type: 'select', filter: '(科索沃|Kosovo)' },
        { name: '🇲🇪 黑山节点', type: 'select', filter: '(黑山|Montenegro)' },
        { name: '🇧🇦 波黑节点', type: 'select', filter: '(波黑|波斯尼亚|Bosnia)' },
        { name: '🇷🇺 俄罗斯节点', type: 'select', filter: '(俄罗斯|俄|RU|Russia|莫斯科|圣彼得堡|Moscow)' },
        { name: '🇺🇦 乌克兰节点', type: 'select', filter: '(乌克兰|Ukraine|基辅)' },
        { name: '🇧🇾 白俄罗斯节点', type: 'select', filter: '(白俄罗斯|Belarus|明斯克)' },
        { name: '🇵🇱 波兰节点', type: 'select', filter: '(波兰|Poland|华沙)' },
        { name: '🇨🇿 捷克节点', type: 'select', filter: '(捷克|Czech|布拉格)' },
        { name: '🇸🇰 斯洛伐克节点', type: 'select', filter: '(斯洛伐克|Slovakia|布拉迪斯拉发)' },
        { name: '🇭🇺 匈牙利节点', type: 'select', filter: '(匈牙利|Hungary|布达佩斯)' },
        { name: '🇷🇴 罗马尼亚节点', type: 'select', filter: '(罗马尼亚|Romania|布加勒斯特)' },
        { name: '🇧🇬 保加利亚节点', type: 'select', filter: '(保加利亚|Bulgaria|索非亚)' },
        { name: '🇲🇩 摩尔多瓦节点', type: 'select', filter: '(摩尔多瓦|Moldova|基希讷乌)' },
        { name: '🇱🇻 拉脱维亚节点', type: 'select', filter: '(拉脱维亚|Latvia|里加)' },
        { name: '🇱🇹 立陶宛节点', type: 'select', filter: '(立陶宛|Lithuania|维尔纽斯)' },
        { name: '🇪🇪 爱沙尼亚节点', type: 'select', filter: '(爱沙尼亚|Estonia|塔林)' },
        { name: '🇸🇮 斯洛文尼亚节点', type: 'select', filter: '(斯洛文尼亚|Slovenia|卢布尔雅那)' },
        { name: '🇭🇷 克罗地亚节点', type: 'select', filter: '(克罗地亚|Croatia|萨格勒布)' },
        { name: '🇷🇸 塞尔维亚节点', type: 'select', filter: '(塞尔维亚|Serbia|贝尔格莱德)' },
        { name: '🇦🇺 澳洲节点', type: 'select', filter: '(澳洲|澳大利亚|AU|Australia|悉尼|墨尔本|Sydney|Melbourne)' },
        { name: '🇳🇿 新西兰节点', type: 'select', filter: '(新西兰|New Zealand|奥克兰)' },
        { name: '🇫🇯 斐济节点', type: 'select', filter: '(斐济|Fiji|苏瓦)' },
        { name: '🇵🇬 巴新节点', type: 'select', filter: '(巴布亚新几内亚|巴新|Papua New Guinea)' },
        { name: '🇼🇸 萨摩亚节点', type: 'select', filter: '(萨摩亚|Samoa)' },
        { name: '🇹🇴 汤加节点', type: 'select', filter: '(汤加|Tonga)' },
        { name: '🇻🇺 瓦努阿图节点', type: 'select', filter: '(瓦努阿图|Vanuatu)' },
        { name: '🇸🇧 所罗门群岛节点', type: 'select', filter: '(所罗门群岛|Solomon)' },
        { name: '🇳🇨 新喀里多尼亚节点', type: 'select', filter: '(新喀里多尼亚|New Caledonia)' },
        { name: '🇵🇫 法属波利尼西亚节点', type: 'select', filter: '(法属波利尼西亚|French Polynesia|大溪地)' },
        { name: '🇬🇺 关岛节点', type: 'select', filter: '(关岛|Guam)' },
        { name: '🇪🇬 埃及节点', type: 'select', filter: '(埃及|Egypt|开罗)' },
        { name: '🇱🇾 利比亚节点', type: 'select', filter: '(利比亚|Libya|的黎波里)' },
        { name: '🇹🇳 突尼斯节点', type: 'select', filter: '(突尼斯|Tunisia|突尼斯城)' },
        { name: '🇩🇿 阿尔及利亚节点', type: 'select', filter: '(阿尔及利亚|Algeria|阿尔及尔)' },
        { name: '🇲🇦 摩洛哥节点', type: 'select', filter: '(摩洛哥|Morocco|卡萨布兰卡)' },
        { name: '🇸🇩 苏丹节点', type: 'select', filter: '(苏丹|Sudan|喀土穆)' },
        { name: '🇳🇬 尼日利亚节点', type: 'select', filter: '(尼日利亚|Nigeria|拉各斯)' },
        { name: '🇬🇭 加纳节点', type: 'select', filter: '(加纳|Ghana|阿克拉)' },
        { name: '🇸🇳 塞内加尔节点', type: 'select', filter: '(塞内加尔|Senegal|达喀尔)' },
        { name: '🇨🇮 科特迪瓦节点', type: 'select', filter: '(科特迪瓦|象牙海岸|Ivory Coast|Cote)' },
        { name: '🇲🇱 马里节点', type: 'select', filter: '(马里|Mali|巴马科)' },
        { name: '🇧🇫 布基纳法索节点', type: 'select', filter: '(布基纳法索|Burkina Faso)' },
        { name: '🇳🇪 尼日尔节点', type: 'select', filter: '(尼日尔|Niger)' },
        { name: '🇬🇳 几内亚节点', type: 'select', filter: '(几内亚|Guinea)' },
        { name: '🇹🇬 多哥节点', type: 'select', filter: '(多哥|Togo)' },
        { name: '🇧🇯 贝宁节点', type: 'select', filter: '(贝宁|Benin)' },
        { name: '🇱🇷 利比里亚节点', type: 'select', filter: '(利比里亚|Liberia)' },
        { name: '🇸🇱 塞拉利昂节点', type: 'select', filter: '(塞拉利昂|Sierra Leone)' },
        { name: '🇲🇷 毛里塔尼亚节点', type: 'select', filter: '(毛里塔尼亚|Mauritania)' },
        { name: '🇬🇲 冈比亚节点', type: 'select', filter: '(冈比亚|Gambia)' },
        { name: '🇨🇻 佛得角节点', type: 'select', filter: '(佛得角|Cape Verde)' },
        { name: '🇨🇲 喀麦隆节点', type: 'select', filter: '(喀麦隆|Cameroon|雅温得)' },
        { name: '🇨🇩 刚果金节点', type: 'select', filter: '(刚果民主共和国|刚果金|DR Congo)' },
        { name: '🇨🇬 刚果布节点', type: 'select', filter: '(刚果共和国|刚果布|Congo)' },
        { name: '🇨🇫 中非节点', type: 'select', filter: '(中非共和国|中非|Central African)' },
        { name: '🇹🇩 乍得节点', type: 'select', filter: '(乍得|Chad)' },
        { name: '🇬🇦 加蓬节点', type: 'select', filter: '(加蓬|Gabon)' },
        { name: '🇬🇶 赤道几内亚节点', type: 'select', filter: '(赤道几内亚|Equatorial Guinea)' },
        { name: '🇰🇪 肯尼亚节点', type: 'select', filter: '(肯尼亚|Kenya|内罗毕)' },
        { name: '🇹🇿 坦桑尼亚节点', type: 'select', filter: '(坦桑尼亚|Tanzania|达累斯萨拉姆)' },
        { name: '🇺🇬 乌干达节点', type: 'select', filter: '(乌干达|Uganda|坎帕拉)' },
        { name: '🇷🇼 卢旺达节点', type: 'select', filter: '(卢旺达|Rwanda|基加利)' },
        { name: '🇧🇮 布隆迪节点', type: 'select', filter: '(布隆迪|Burundi)' },
        { name: '🇪🇹 埃塞俄比亚节点', type: 'select', filter: '(埃塞俄比亚|Ethiopia|亚的斯亚贝巴)' },
        { name: '🇪🇷 厄立特里亚节点', type: 'select', filter: '(厄立特里亚|Eritrea)' },
        { name: '🇩🇯 吉布提节点', type: 'select', filter: '(吉布提|Djibouti)' },
        { name: '🇸🇴 索马里节点', type: 'select', filter: '(索马里|Somalia)' },
        { name: '🇲🇬 马达加斯加节点', type: 'select', filter: '(马达加斯加|Madagascar)' },
        { name: '🇲🇺 毛里求斯节点', type: 'select', filter: '(毛里求斯|Mauritius)' },
        { name: '🇸🇨 塞舌尔节点', type: 'select', filter: '(塞舌尔|Seychelles)' },
        { name: '🇰🇲 科摩罗节点', type: 'select', filter: '(科摩罗|Comoros)' },
        { name: '🇷🇪 留尼汪节点', type: 'select', filter: '(留尼汪|Reunion)' },
        { name: '🇿🇦 南非节点', type: 'select', filter: '(南非|South Africa|约翰内斯堡|开普敦)' },
        { name: '🇿🇼 津巴布韦节点', type: 'select', filter: '(津巴布韦|Zimbabwe|哈拉雷)' },
        { name: '🇿🇲 赞比亚节点', type: 'select', filter: '(赞比亚|Zambia|卢萨卡)' },
        { name: '🇲🇼 马拉维节点', type: 'select', filter: '(马拉维|Malawi)' },
        { name: '🇲🇿 莫桑比克节点', type: 'select', filter: '(莫桑比克|Mozambique|马普托)' },
        { name: '🇧🇼 博茨瓦纳节点', type: 'select', filter: '(博茨瓦纳|Botswana)' },
        { name: '🇳🇦 纳米比亚节点', type: 'select', filter: '(纳米比亚|Namibia|温得和克)' },
        { name: '🇦🇴 安哥拉节点', type: 'select', filter: '(安哥拉|Angola|罗安达)' },
        { name: '🇸🇿 斯威士兰节点', type: 'select', filter: '(斯威士兰|Eswatini|Swaziland)' },
        { name: '🇱🇸 莱索托节点', type: 'select', filter: '(莱索托|Lesotho)' }
    ]
};
